stages:
  - build
  - test

before_script:
  - apt-get update --yes
  - apt-get upgrade --yes
  - DEBIAN_FRONTEND="noninteractive" apt-get install --yes tzdata
  - apt-get install --yes gcc-10 g++-10 cmake clang-tidy libglu1-mesa-dev xorg-dev

build:gcc:
  stage: build
  image: "ubuntu:latest"
  script:
    - mkdir build_gcc
    - cd build_gcc
    - cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --target visualizer
    - cmake --build . --target visualizer_main
    - cmake --build . --target visualizer_tests
  artifacts:
    paths:
      - build_gcc

test:gcc:
  stage: test
  image: "ubuntu:latest"
  script:
    - cd build_gcc/test
    - ./visualizer_tests